import { createTheme } from "@fluentui/react";

export const DarkTheme = createTheme({
  palette: {
    themePrimary: "#3292db",
    themeLighterAlt: "#020609",
    themeLighter: "#081723",
    themeLight: "#0f2c42",
    themeTertiary: "#1e5884",
    themeSecondary: "#2c81c1",
    themeDarkAlt: "#449cdf",
    themeDark: "#5faae4",
    themeDarker: "#86bfeb",
    neutralLighterAlt: "#222426",
    neutralLighter: "#2a2d2f",
    neutralLight: "#373b3d",
    neutralQuaternaryAlt: "#404446",
    neutralQuaternary: "#464b4d",
    neutralTertiaryAlt: "#64696b",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#181a1b",
  },
});

export const LightTheme = createTheme({
  palette: {
    themePrimary: "#e40712",
    themeLighterAlt: "#fef4f5",
    themeLighter: "#fbd4d6",
    themeLight: "#f7afb2",
    themeTertiary: "#ee646a",
    themeSecondary: "#e6222c",
    themeDarkAlt: "#cc0610",
    themeDark: "#ac050e",
    themeDarker: "#7f040a",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
});

export const DarkPurpleTheme = createTheme({
  palette: {
    themePrimary: "#b15beb",
    themeLighterAlt: "#070409",
    themeLighter: "#1c0f26",
    themeLight: "#351b46",
    themeTertiary: "#6a378d",
    themeSecondary: "#9c51ce",
    themeDarkAlt: "#b96bed",
    themeDark: "#c380ef",
    themeDarker: "#d2a0f4",
    neutralLighterAlt: "#181a1b",
    neutralLighter: "#181a1b",
    neutralLight: "#17191a",
    neutralQuaternaryAlt: "#151718",
    neutralQuaternary: "#141617",
    neutralTertiaryAlt: "#141516",
    neutralTertiary: "#c8c8c8",
    neutralSecondary: "#d0d0d0",
    neutralPrimaryAlt: "#dadada",
    neutralPrimary: "#ffffff",
    neutralDark: "#f4f4f4",
    black: "#f8f8f8",
    white: "#181a1b",
  },
});

export const LightPurpleTheme = createTheme({
  palette: {
    themePrimary: "#9f2de0",
    themeLighterAlt: "#fbf6fe",
    themeLighter: "#eedafa",
    themeLight: "#e0bbf6",
    themeTertiary: "#c37bed",
    themeSecondary: "#a944e4",
    themeDarkAlt: "#8f28ca",
    themeDark: "#7922ab",
    themeDarker: "#59197e",
    neutralLighterAlt: "#faf9f8",
    neutralLighter: "#f3f2f1",
    neutralLight: "#edebe9",
    neutralQuaternaryAlt: "#e1dfdd",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c6c4",
    neutralTertiary: "#a19f9d",
    neutralSecondary: "#605e5c",
    neutralPrimaryAlt: "#3b3a39",
    neutralPrimary: "#323130",
    neutralDark: "#201f1e",
    black: "#000000",
    white: "#ffffff",
  },
});
